version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app  
    restart: always
    networks:
      - app-network
    env_file:
      - .env
    environment:
      DB_HOST: db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db_data:
